server:
  port: ${PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: super-rps-backend
  
  # 数据库配置（支持环境变量，用于云部署）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/super_rps?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456789}
    
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.superrps.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置（支持环境变量）
jwt:
  secret: ${JWT_SECRET:SuperRPS-Secret-Key-2025-Change-This-In-Production-Environment}
  expiration: ${JWT_EXPIRATION:604800000}  # 7天（毫秒）

# 日志配置
logging:
  level:
    com.example.superrps: debug
    org.springframework.web: info

